"""initial schema

Revision ID: ae8b87b0760c
Revises:
Create Date: 2026-04-19 16:38:36.032628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ae8b87b0760c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("secret_type", sa.String(length=100), nullable=False),
        sa.Column("framework", sa.String(length=50), nullable=False),
        sa.Column("control_id", sa.String(length=50), nullable=False),
        sa.Column("control_title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_name", sa.String(length=255), nullable=False),
        sa.Column("scan_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("repos_total", sa.Integer(), nullable=True),
        sa.Column("repos_scanned", sa.Integer(), nullable=True),
        sa.Column("current_repo", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_scans_session", "scans", ["session_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=True),
        sa.Column("dedup_hash", sa.String(length=64), nullable=False),
        sa.Column("repo_name", sa.String(length=255), nullable=False),
        sa.Column("secret_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("commit_date", sa.DateTime(), nullable=True),
        sa.Column("commit_author", sa.String(length=255), nullable=True),
        sa.Column("commit_message", sa.Text(), nullable=True),
        sa.Column("branch_status", sa.String(length=20), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.Column("redacted_secret", sa.Text(), nullable=True),
        sa.Column("raw_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("commit_shas", sa.JSON(), nullable=True),
        sa.Column(
            "raw_detector_output",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "dedup_hash", name="uq_findings_dedup"),
    )
    op.create_index("idx_findings_scan_id", "findings", ["scan_id"], unique=False)
    op.create_table(
        "search_hits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=True),
        sa.Column("repo_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("matched_pattern", sa.String(length=100), nullable=False),
        sa.Column("text_fragment", sa.Text(), nullable=True),
        sa.Column("html_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_search_hits_scan_id", "search_hits", ["scan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_search_hits_scan_id", table_name="search_hits")
    op.drop_table("search_hits")
    op.drop_index("idx_findings_scan_id", table_name="findings")
    op.drop_table("findings")
    op.drop_index("idx_scans_session", table_name="scans")
    op.drop_table("scans")
    op.drop_table("compliance_mappings")
    # ### end Alembic commands ###
